[import-byreplication] name2infoxml gets *last* num, not current num

diff --git a/cvnsnapper-import-byreplication b/cvnsnapper-import-byreplication
--- a/cvnsnapper-import-byreplication
+++ b/cvnsnapper-import-byreplication
@@ -11,7 +11,7 @@ die() {
 
 
 LAST_SNAPSHOT_SUBVOL=
-DEST_N=0
+DEST_LAST_NUM=0
 DEST_DOT_SNAPSHOTS_SUBVOL=
 
 if [ -z "$CVNSNAPPER_IMPORT_NAME2INFOXML_BIN" ] && ! type -p cvnsnapper-import-name2infoxml &>/dev/null
@@ -41,7 +41,7 @@ do
 		shift
 		;;
 	--dest-last-num=*)
-		DEST_N="${1#--dest-last-num=}"
+		DEST_LAST_NUM="${1#--dest-last-num=}"
 		shift
 		;;
 	--dest-snapshots-subvol=*)
@@ -63,10 +63,9 @@ done
 
 for SNAPSHOT_SUBVOL
 do
-	: $[DEST_N++]
-
 	SNAPSHOT_BASENAME="${SNAPSHOT_SUBVOL#*/}"
 	SNAPSHOT_NAME="${SNAPSHOT_BASENAME#*@}"
+	DEST_N="$[DEST_LAST_NUM+1]"
 
 	#
 	# Consider plain snapshot name verbosely.
@@ -77,7 +76,7 @@ do
 	DEST_DIR="$DEST_DOT_SNAPSHOTS_SUBVOL/$DEST_N"
 	[ -e "$DEST_DIR" ] && { echo "(error)"; die "Destination directory \"$DEST_DIR\" already exists for source plain snapshot \"$SNAPSHOT_SUBVOL\""; }
 
-	"${CVNSNAPPER_IMPORT_NAME2INFOXML_BIN:-cvnsnapper-import-name2infoxml}" --last-num="$DEST_N" --create-in-snapshots-subvol="$DEST_DOT_SNAPSHOTS_SUBVOL" "$SNAPSHOT_NAME" || { echo "(error)"; die "Creating destination snapper snapshot meta-data in \"$DEST_DOT_SNAPSHOTS_SUBVOL\" failed for source plain snapshot \"$SNAPSHOT_SUBVOL\""; }
+	"${CVNSNAPPER_IMPORT_NAME2INFOXML_BIN:-cvnsnapper-import-name2infoxml}" --last-num="$DEST_LAST_NUM" --create-in-snapshots-subvol="$DEST_DOT_SNAPSHOTS_SUBVOL" "$SNAPSHOT_NAME" || { echo "(error)"; die "Creating destination snapper snapshot meta-data in \"$DEST_DOT_SNAPSHOTS_SUBVOL\" failed for source plain snapshot \"$SNAPSHOT_SUBVOL\""; }
 	[ -d "$DEST_DIR" ] || { echo "(error)"; die "cvnsnapper-import-name2infoxml apparently failed to create destination directory \"$DEST_DIR\" for source plain snapshot \"$SNAPSHOT_SUBVOL\""; }
 	[ -f "$DEST_DIR/info.xml" ] || { echo "(error)"; die "cvnsnapper-import-name2infoxml apparently failed to create destination directory \"$DEST_DIR\" for source plain snapshot \"$SNAPSHOT_SUBVOL\""; }
 
@@ -90,6 +89,7 @@ do
 
 	# Remember this snapshot as parent for the transfer of the next snapshot.
 	LAST_SNAPSHOT_SUBVOL="$SNAPSHOT_SUBVOL"
+	DEST_LAST_NUM="$DEST_N"
 done
 
 exit 0
