[genmetadata] Execute find cd'ed to the subvolume
This avoids having the subvolume's name spelt out in the stat log file
again and again.

As it would be difficult to impossible (depending on the situation)
to give a relative path from cd'ed to the subvolume to the log file
outside, the log file is opened by the shell script and passed as a
file descriptor number in the environment, instead.

diff --git a/cvnsnapper-replicate-genmetadata b/cvnsnapper-replicate-genmetadata
--- a/cvnsnapper-replicate-genmetadata
+++ b/cvnsnapper-replicate-genmetadata
@@ -37,10 +37,20 @@ do
 
 	[ -e "$SUBVOL_STAT_LOG" ] && die "Stat log file for btrfs subvolume \"$SUBVOL\" already exists: $SUBVOL_STAT_LOG"
 
+	exec {SUBVOL_STAT_LOG_FD}>>"$SUBVOL_STAT_LOG" || die "Couldn't open stat log file for btrfs subvolume \"$SUBVOL\": $SUBVOL_STAT_LOG"
+	export SUBVOL_STAT_LOG_FD
+
 
 	echo "Processing btrfs subvolume $SUBVOL ..."
 
-	find "$SUBVOL" \
-		! -path "$SUBVOL" -inum 256 -printf "Pruning child subvolume %p\n" -prune , \
-		-exec bash -c "stat -- \"\$@\" >>\"\$SUBVOL_STAT_LOG\"" stat-log "{}" +
+	( cd "$SUBVOL" && find \
+		! -path . -inum 256 -printf "Pruning child subvolume %p\n" -prune , \
+		-exec bash -c "stat -- \"\$@\" >&\"\$SUBVOL_STAT_LOG_FD\"" stat-log "{}" +
+	)
+
+
+	exec {SUBVOL_STAT_LOG_FD}>&- || die "Couldn't close stat log file for btrfs subvolume \"$SUBVOL\": $SUBVOL_STAT_LOG"
+	unset \
+		SUBVOL_STAT_LOG_FD \
+		SUBVOL_STAT_LOG
 done
