replicate-send: --receive: Increase UUID extraction compatibility
.., back to btrfs-tools 3.17-1.1 from Debian 8 'jessie'.

If `btrfs subvolume show ...` doesn't have a received UUID field,
try to extract it from `btrfs subvolume list ...`. Seems to work!

Also, the capitalization of "UUID" is different to Debian 9 'stretch'
btrfs-progs 4.7.3-1.

diff --git a/cvnsnapper-replicate-send b/cvnsnapper-replicate-send
--- a/cvnsnapper-replicate-send
+++ b/cvnsnapper-replicate-send
@@ -73,10 +73,20 @@ then
 		# Sanity check.
 		CHECK_TEXT="connection between last output prefix snapshot and corresponding input snapshot"
 
-		OUT_RECEIVED_UUID="$(btrfs subvolume show "$OUTPUT_SNAPSHOTS/$LAST_SNAPSHOT_NUMBER_ARG/snapshot" | sed -n -e 's/^\s*Received UUID:\s*\([-0-9a-f]*\)$/\1/p')"
-		[ -n "$OUT_RECEIVED_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Couldn't get last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\"'s received UUID"
+		OUT_SNAP="$OUTPUT_SNAPSHOTS/$LAST_SNAPSHOT_NUMBER_ARG/snapshot"
+		OUT_RECEIVED_UUID="$(btrfs subvolume show "$OUT_SNAP" | sed -n -e 's/^\s*Received UUID:\s*\([-0-9a-f]*\)$/\1/ip')"
+		[ "$OUT_RECEIVED_UUID" = "-" ] && die "Failed to sanity-check $CHECK_TEXT: Invalid received UUID \"$OUT_RECEIVED_UUID\" of last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\""
+		if [ -z "$OUT_RECEIVED_UUID" ]
+		then
+			OUT_UUID="$(btrfs subvolume show "$OUT_SNAP" | sed -n -e 's/^\s*UUID:\s*\([-0-9a-f]*\)$/\1/ip')"
+			[ -n "$OUT_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Couldn't get neither UUID nor recived UUID of last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\""
 
-		IN_UUID="$(btrfs subvolume show "$LAST_SNAPSHOT_NUMBER_ARG/snapshot" | sed -n -e 's/^\s*UUID:\s*\([-0-9a-f]*\)$/\1/p')"
+			# -u: UUID, -R: received UUID
+			OUT_RECEIVED_UUID="$(btrfs subvolume list -u -R "$OUT_SNAP" | sed -n -e "s/.* received_uuid \\([-0-9a-f]*\\) uuid $OUT_UUID .*/\\1/ip")"
+			[ -n "$OUT_RECEIVED_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Couldn't get last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\"'s received UUID, not even via fall-back method"
+		fi
+
+		IN_UUID="$(btrfs subvolume show "$LAST_SNAPSHOT_NUMBER_ARG/snapshot" | sed -n -e 's/^\s*UUID:\s*\([-0-9a-f]*\)$/\1/ip')"
 		[ -n "$IN_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Couldn't get input snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\"'s UUID"
 
 		[ "$OUT_RECEIVED_UUID" = "$IN_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Received UUID \"$OUT_RECEIVED_UUID\" doesn't match UUID \"$IN_UUID\""
