[genmetadata] Diff: First diff stat log, then diff checksums file
That is, simply exchange both code blocks.

This should make it easier to see meta-data changes, which this
is all about.

diff --git a/cvnsnapper-replicate-genmetadata b/cvnsnapper-replicate-genmetadata
--- a/cvnsnapper-replicate-genmetadata
+++ b/cvnsnapper-replicate-genmetadata
@@ -227,26 +227,6 @@ do
 		SUBVOL_STAT_LOG_PREV="${DIFF_SUBVOL:-$SUBVOL}${DIFF_INFIX}.stat.log"
 		SUBVOL_CHECKSUMS_FILE_PREV="${DIFF_SUBVOL:-$SUBVOL}${DIFF_INFIX}.sha256"
 
-		if ! [ -f "$SUBVOL_CHECKSUMS_FILE_PREV" ]
-		then
-			warn "Warning: Checksums can't be diff'ed for subvol \"$SUBVOL\": Previous checksums file missing or not a regular file: $SUBVOL_CHECKSUMS_FILE_PREV"
-			[ "$RET" -lt 2 ] && RET=2
-			[ "$DIFF_RESULT" -lt 2 ] && DIFF_RESULT=2
-		elif ! [ -f "$SUBVOL_CHECKSUMS_FILE" ]
-		then
-			warn "Warning: Checksums can't be diff'ed for subvol \"$SUBVOL\": Later checksums file missing or not a regular file: $SUBVOL_CHECKSUMS_FILE"
-			[ "$RET" -lt 2 ] && RET=2
-			[ "$DIFF_RESULT" -lt 2 ] && DIFF_RESULT=2
-		else
-			echo "Diffing checksums:"
-			if ! diff <(sort -k2 <"$SUBVOL_CHECKSUMS_FILE_PREV") <(sort -k2 <"$SUBVOL_CHECKSUMS_FILE")
-			then
-				warn "Warning: Checksum differences found for subvol \"$SUBVOL\", from${DIFF_SUBVOL:+ diff subvol \"$DIFF_SUBVOL\"} infix \"$DIFF_INFIX\" to infix \"$INFIX\""
-				[ "$RET" -lt 1 ] && RET=1
-				[ "$DIFF_RESULT" -lt 1 ] && DIFF_RESULT=1
-			fi
-		fi
-
 		if ! [ -f "$SUBVOL_STAT_LOG_PREV" ]
 		then
 			warn "Warning: Stat results can't be diff'ed for subvol \"$SUBVOL\": Previous stat log missing or not a regular file: $SUBVOL_STAT_LOG_PREV"
@@ -269,6 +249,26 @@ do
 				<(sort-stat <"$SUBVOL_STAT_LOG"      | filter-stat)
 			then
 				warn "Warning: stat differences found for subvol \"$SUBVOL\", from${DIFF_SUBVOL:+ diff subvol \"$DIFF_SUBVOL\"} infix \"$DIFF_INFIX\" to infix \"$INFIX\""
+				[ "$RET" -lt 1 ] && RET=1
+				[ "$DIFF_RESULT" -lt 1 ] && DIFF_RESULT=1
+			fi
+		fi
+
+		if ! [ -f "$SUBVOL_CHECKSUMS_FILE_PREV" ]
+		then
+			warn "Warning: Checksums can't be diff'ed for subvol \"$SUBVOL\": Previous checksums file missing or not a regular file: $SUBVOL_CHECKSUMS_FILE_PREV"
+			[ "$RET" -lt 2 ] && RET=2
+			[ "$DIFF_RESULT" -lt 2 ] && DIFF_RESULT=2
+		elif ! [ -f "$SUBVOL_CHECKSUMS_FILE" ]
+		then
+			warn "Warning: Checksums can't be diff'ed for subvol \"$SUBVOL\": Later checksums file missing or not a regular file: $SUBVOL_CHECKSUMS_FILE"
+			[ "$RET" -lt 2 ] && RET=2
+			[ "$DIFF_RESULT" -lt 2 ] && DIFF_RESULT=2
+		else
+			echo "Diffing checksums:"
+			if ! diff <(sort -k2 <"$SUBVOL_CHECKSUMS_FILE_PREV") <(sort -k2 <"$SUBVOL_CHECKSUMS_FILE")
+			then
+				warn "Warning: Checksum differences found for subvol \"$SUBVOL\", from${DIFF_SUBVOL:+ diff subvol \"$DIFF_SUBVOL\"} infix \"$DIFF_INFIX\" to infix \"$INFIX\""
 				[ "$RET" -lt 1 ] && RET=1
 				[ "$DIFF_RESULT" -lt 1 ] && DIFF_RESULT=1
 			fi
