[plain-backingstorage] Upgrade from integer to floating point
.., as a size of "1 TiB" for a nearly 2 TiB drive is ridiculous
and/or misleading.

The downside is that we seem to have to carry around more embedded
Perl scripts.

diff --git a/cvnsnapper-plain-backingstorage b/cvnsnapper-plain-backingstorage
--- a/cvnsnapper-plain-backingstorage
+++ b/cvnsnapper-plain-backingstorage
@@ -17,40 +17,27 @@ size-to-unit() {
 	[ "$#" -eq 2 ] || die "Internal error: size-to-unit needs exactly two arguments, the size and the unit"
 	local SIZE="$1"; shift
 	local UNIT="$1"; shift
-	case "$UNIT" in
-	TiB)
-		echo "$[SIZE / 1024**4] TiB"
-		;;
-	TB)
-		echo "$[SIZE / 1000**4] TB"
-		;;
-	GiB)
-		echo "$[SIZE / 1024**3] GiB"
-		;;
-	GB)
-		echo "$[SIZE / 1000**3] GB"
-		;;
-	MiB)
-		echo "$[SIZE / 1024**2] MiB"
-		;;
-	MB)
-		echo "$[SIZE / 1000**2] MB"
-		;;
-	KiB)
-		echo "$[SIZE / 1024**1] KiB"
-		;;
-	KB)
-		echo "$[SIZE / 1000**1] KB"
-		;;
-	B)
-		echo "$[SIZE] B"
-		;;
-	*)
-		warn "Internal error: size-to-unit got request for unrecognized unit \"$UNIT\""
-		return 1
-		;;
-	esac
-	return 0
+	perl -le "
+		use strict;
+		use warnings;
+		my \$size = \"$SIZE\";
+		my \$unit = \"$UNIT\";
+		my %unit_to_factor = (
+			TiB => 1024**4, GiB => 1024**3, MiB => 1024**2, KiB => 1024**1,
+			TB  => 1000**4, GB  => 1000**3, MB  => 1000**2, KB  => 1000**1,
+			B   => 1
+		);
+		die(\"Internal error: size-to-unit got request for unrecognized unit \\\"\$unit\\\"\")
+		  unless exists(\$unit_to_factor{\$unit});
+		my \$factor = \$unit_to_factor{\$unit};
+		if (\$factor == 1) {
+			print(\"\$size \$unit\");
+		}
+		else {
+			my \$size_unit = \$size / \$factor;
+			printf('%.2f %s', \$size_unit, \$unit);
+		}
+	"
 }
 
 size-to-some-unit() {
@@ -106,7 +93,7 @@ size-to-some-unit() {
 
 		local UNIT_SIZE DUMMY
 		read UNIT_SIZE DUMMY <<<"$UNIT_SIZE_STR"
-		[ "$UNIT_SIZE" -gt 0 ] || continue
+		perl -e "\"$UNIT_SIZE\" >= 0.5 && exit(0); exit(1);" || continue
 
 		if [ "$UNIT" = "B" ]
 		then
