[import-byreplication] Allow finding & overriding cvnsnapper-import-name2infoxml location
* Allow setting/overriding path to cvnsnapper-import-name2infoxml
  via environment variable CVNSNAPPER_IMPORT_NAME2INFOXML_BIN.
* If not set and cvnsnapper-import-name2infoxml is not on the path,
  try to point it to the name2infoxml from the same directory
  as this script was called.
* Try to use the environment variable when invoking
  cvnsnapper-import-name2infoxml, but fall back to the command name.

diff --git a/cvnsnapper-import-byreplication b/cvnsnapper-import-byreplication
--- a/cvnsnapper-import-byreplication
+++ b/cvnsnapper-import-byreplication
@@ -14,6 +14,16 @@ LAST_SNAPSHOT_SUBVOL=
 DEST_N=0
 DEST_DOT_SNAPSHOTS_SUBVOL=
 
+if [ -z "$CVNSNAPPER_IMPORT_NAME2INFOXML_BIN" ] && ! type -p cvnsnapper-import-name2infoxml &>/dev/null
+then
+	if [ "${0%/*}" != "$0" ]
+	then
+		CVNSNAPPER_IMPORT_NAME2INFOXML_BIN="${0%/*}/cvnsnapper-import-name2infoxml"
+	fi
+
+	[ -x "$CVNSNAPPER_IMPORT_NAME2INFOXML_BIN" ] || die "Cannot find cvnsnapper-import-name2infoxml, please specify via environment variable CVNSNAPPER_IMPORT_NAME2INFOXML_BIN"
+fi
+
 USAGE="Usage: $0 [--last-snapshot=LAST_SNAPSHOT_SUBVOL] [--dest-last-num=N] --dest-snapshots-subvol=DEST_DOT_SNAPSHOTS_SUBVOL SNAPSHOT_SUBVOL [...]"
 
 while [ "$#" -ge 1 ] && [ "${1:0:1}" = "-" ]
@@ -67,7 +77,7 @@ do
 	DEST_DIR="$DEST_DOT_SNAPSHOTS_SUBVOL/$DEST_N"
 	[ -e "$DEST_DIR" ] && { echo "(error)"; die "Destination directory \"$DEST_DIR\" already exists for source plain snapshot \"$SNAPSHOT_SUBVOL\""; }
 
-	cvnsnapper-import-name2infoxml --last-num="$DEST_N" --create-in-snapshots-subvol="$DEST_DOT_SNAPSHOTS_SUBVOL" "$SNAPSHOT_NAME" || { echo "(error)"; die "Creating destination snapper snapshot meta-data in \"$DEST_DOT_SNAPSHOTS_SUBVOL\" failed for source plain snapshot \"$SNAPSHOT_SUBVOL\""; }
+	"${CVNSNAPPER_IMPORT_NAME2INFOXML_BIN:-cvnsnapper-import-name2infoxml}" --last-num="$DEST_N" --create-in-snapshots-subvol="$DEST_DOT_SNAPSHOTS_SUBVOL" "$SNAPSHOT_NAME" || { echo "(error)"; die "Creating destination snapper snapshot meta-data in \"$DEST_DOT_SNAPSHOTS_SUBVOL\" failed for source plain snapshot \"$SNAPSHOT_SUBVOL\""; }
 	[ -d "$DEST_DIR" ] || { echo "(error)"; die "cvnsnapper-import-name2infoxml apparently failed to create destination directory \"$DEST_DIR\" for source plain snapshot \"$SNAPSHOT_SUBVOL\""; }
 	[ -f "$DEST_DIR/info.xml" ] || { echo "(error)"; die "cvnsnapper-import-name2infoxml apparently failed to create destination directory \"$DEST_DIR\" for source plain snapshot \"$SNAPSHOT_SUBVOL\""; }
 
