[plain-backingstorage] Implement option parsing

diff --git a/cvnsnapper-plain-backingstorage b/cvnsnapper-plain-backingstorage
--- a/cvnsnapper-plain-backingstorage
+++ b/cvnsnapper-plain-backingstorage
@@ -12,4 +12,37 @@ die() {
 	exit 1
 }
 
-die "Not implemented, yet."
+
+USAGE="cvnsnapper-plain-backingstorage show BTRFS_MOUNT_POINT"
+
+while [ "$#" -gt 0 ] && [ "${1:0:1}" = "-" ]
+do
+	OPTION="$1"
+	shift
+
+	case "$OPTION" in
+	--help|--usage|-\?)
+		echo "Usage: $USAGE"
+		exit 0
+		;;
+	*)
+		die "Invalid option \"$OPTION\""
+		;;
+	esac
+done
+
+[ "$#" -ge 1 ] || die "Usage: $USAGE"
+
+MODE="$1"
+shift
+
+case "$MODE" in
+show)
+	die "Mode-of-operation \"$MODE\": Not implemented, yet."
+	;;
+*)
+	die "Invalid mode-of-operation \"$MODE\""
+	;;
+esac
+
+exit 0
