replicate-{send,receive}: Factor out subvol_get{,_received}_uuid() to libbtrfs.sh

diff --git a/lib/cvnsnapper-toolbox/replicate-receive b/lib/cvnsnapper-toolbox/replicate-receive
--- a/lib/cvnsnapper-toolbox/replicate-receive
+++ b/lib/cvnsnapper-toolbox/replicate-receive
@@ -48,19 +48,8 @@ protomsg_receivedUUID() {
 	[ -n "$CST_SNAPSHOT_NUMBER" ] || die "Can't send protocol message \"receivedUUID\" as the current snapshot number is not set"
 
 	CST_SNAP="$CST_OUTPUT_SNAPSHOTS/$CST_SNAPSHOT_NUMBER/snapshot"
-	CST_RECEIVED_UUID="$(btrfs subvolume show "$CST_SNAP" | sed -n -e 's/^\s*Received UUID:\s*\([-0-9a-f]*\)$/\1/ip')"
-	[ "$CST_RECEIVED_UUID" = "-" ] && die "Failed to retrieve received UUID for snapshot \"$CST_SNAPSHOT_NUMBER\": Invalid received UUID \"$CST_RECEIVED_UUID\""
-	if [ -z "$CST_RECEIVED_UUID" ]
-	then
-		# Work-around for older versions of btrfs command:
-
-		CST_UUID="$(btrfs subvolume show "$CST_SNAP" | sed -n -e 's/^\s*UUID:\s*\([-0-9a-f]*\)$/\1/ip')"
-		[ -n "$CST_UUID" ] || die "Failed to retrieve received UUID for snapshot \"$CST_SNAPSHOT_NUMBER\", work-around for older btrfs command: Couldn't get UUID"
-
-		# -u: UUID, -R: received UUID
-		CST_RECEIVED_UUID="$(btrfs subvolume list -u -R "$CST_SNAP" | sed -n -e "s/.* received_uuid \\([-0-9a-f]*\\) uuid $CST_UUID .*/\\1/ip")"
-		[ -n "$CST_RECEIVED_UUID" ] || die "Failed to retrieve received UUID for snapshot \"$CST_SNAPSHOT_NUMBER\", work-around for older btrfs command: Couldn't get received UUID"
-	fi
+	CST_RECEIVED_UUID="$(subvol_get_received_uuid "$CST_SNAP")" || die "Couldn't retrieve received UUID for snapshot \"$CST_SNAPSHOT_NUMBER\""
+	[ "$CST_RECEIVED_UUID" = "-" ] && die "Received UUID for snapshot \"$CST_SNAPSHOT_NUMBER\" invalid: \"$CST_RECEIVED_UUID\""
 
 	echo "$CST_THIS_SIDE receivedUUID $CST_SNAPSHOT_NUMBER $CST_RECEIVED_UUID"
 }
diff --git a/lib/cvnsnapper-toolbox/replicate-send b/lib/cvnsnapper-toolbox/replicate-send
--- a/lib/cvnsnapper-toolbox/replicate-send
+++ b/lib/cvnsnapper-toolbox/replicate-send
@@ -168,24 +168,14 @@ then
 		CHECK_TEXT="connection between last output prefix snapshot and corresponding input snapshot"
 
 		OUT_SNAP="$OUTPUT_SNAPSHOTS/$LAST_SNAPSHOT_NUMBER_ARG/snapshot"
-		OUT_RECEIVED_UUID="$(btrfs subvolume show "$OUT_SNAP" | sed -n -e 's/^\s*Received UUID:\s*\([-0-9a-f]*\)$/\1/ip')"
+		OUT_RECEIVED_UUID="$(subvol_get_received_uuid "$OUT_SNAP")" || die "Failed to sanity-check $CHECK_TEXT: Failed to get received UUID of last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\""
 		[ "$OUT_RECEIVED_UUID" = "-" ] && die "Failed to sanity-check $CHECK_TEXT: Invalid received UUID \"$OUT_RECEIVED_UUID\" of last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\""
-		if [ -z "$OUT_RECEIVED_UUID" ]
-		then
-			OUT_UUID="$(btrfs subvolume show "$OUT_SNAP" | sed -n -e 's/^\s*UUID:\s*\([-0-9a-f]*\)$/\1/ip')"
-			[ -n "$OUT_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Couldn't get neither UUID nor received UUID of last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\""
-
-			# -u: UUID, -R: received UUID
-			OUT_RECEIVED_UUID="$(btrfs subvolume list -u -R "$OUT_SNAP" | sed -n -e "s/.* received_uuid \\([-0-9a-f]*\\) uuid $OUT_UUID .*/\\1/ip")"
-			[ -n "$OUT_RECEIVED_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Couldn't get last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\"'s received UUID, not even via fall-back method"
-		fi
 	fi
 fi
 
 case "$MODE" in
 remote|sendreceive)
-	IN_UUID="$(btrfs subvolume show "$LAST_SNAPSHOT_NUMBER_ARG/snapshot" | sed -n -e 's/^\s*UUID:\s*\([-0-9a-f]*\)$/\1/ip')"
-	[ -n "$IN_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Couldn't get input snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\"'s UUID"
+	IN_UUID="$(subvol_get_uuid "$LAST_SNAPSHOT_NUMBER_ARG/snapshot")" || die "Failed to sanity-check $CHECK_TEXT: Couldn't get input snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\"'s UUID"
 
 	[ "$OUT_RECEIVED_UUID" = "$IN_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Received UUID \"$OUT_RECEIVED_UUID\" doesn't match UUID \"$IN_UUID\""
 	;;
