replicate-send: die(): Bugfix: Try to close the SSH input fd more correctly
Seems to be formally correct, now, but doesn't help with the problem
(of the SSH connection hanging after error, until, e.g., pressing ^C).

diff --git a/lib/cvnsnapper-toolbox/replicate-send b/lib/cvnsnapper-toolbox/replicate-send
--- a/lib/cvnsnapper-toolbox/replicate-send
+++ b/lib/cvnsnapper-toolbox/replicate-send
@@ -10,7 +10,11 @@ die() {
 	warn "Fatal: $*"
 
 	# Close SSH stdin pipe fd, to allow the connection to die.
-	[ -n "$CST_SSH_STDIN" ] && exec "$CST_SSH_STDIN">&-
+	# (But, in fact, doesn't seem to help. ..?)
+	if [ -n "$CST_SSH_STDIN" ]
+	then
+		exec {CST_SSH_STDIN}>&- || warn "Failed to close SSH standard input"
+	fi
 
 	exit 1
 }
