replicate-send: (Fix typo in error message)

diff --git a/lib/cvnsnapper-toolbox/replicate-send b/lib/cvnsnapper-toolbox/replicate-send
--- a/lib/cvnsnapper-toolbox/replicate-send
+++ b/lib/cvnsnapper-toolbox/replicate-send
@@ -79,7 +79,7 @@ then
 		if [ -z "$OUT_RECEIVED_UUID" ]
 		then
 			OUT_UUID="$(btrfs subvolume show "$OUT_SNAP" | sed -n -e 's/^\s*UUID:\s*\([-0-9a-f]*\)$/\1/ip')"
-			[ -n "$OUT_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Couldn't get neither UUID nor recived UUID of last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\""
+			[ -n "$OUT_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Couldn't get neither UUID nor received UUID of last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\""
 
 			# -u: UUID, -R: received UUID
 			OUT_RECEIVED_UUID="$(btrfs subvolume list -u -R "$OUT_SNAP" | sed -n -e "s/.* received_uuid \\([-0-9a-f]*\\) uuid $OUT_UUID .*/\\1/ip")"
