replicate-{send,receive}: Transfer info.xml, too
* Increase protocol level to 2.
* Send/receive info.xml data (base64) & timestamp (ISO 8601 date/time
  to nanoseconds precision) when in protocol level 2 or higher.

diff --git a/lib/cvnsnapper-toolbox/replicate-receive b/lib/cvnsnapper-toolbox/replicate-receive
--- a/lib/cvnsnapper-toolbox/replicate-receive
+++ b/lib/cvnsnapper-toolbox/replicate-receive
@@ -21,7 +21,7 @@ CST_USAGE="Usage: $0 OUTPUT_SUBVOL"
 
 CST_THIS_SIDE="CVNSNAPPER_REPLICATE_RECEIVER"
 CST_THIS_PROTO_MIN=0
-CST_THIS_PROTO=1
+CST_THIS_PROTO=2
 
 
 [ "$#" -ge 1 ] || die "$CST_USAGE"
@@ -128,6 +128,15 @@ do
 		# ^ The -e lets btrfs receive end at an end-marker, instead of only on EOF (which we don't have).
 		#   The >&2 is an attempt to get the "At ..." message to the error stream, where it won't gobble up our protocol messages.
 		CST_RECEIVED_SNAPNUMS="$CST_RECEIVED_SNAPNUMS $CST_RECEIVE_SNAPSHOT_NUMBER"
+
+		# Since protocol 2, we'll also receive the snapper info.xml, in-band.
+		if [ "$CST_STATE_OTHER_PROTO" -ge 2 ]
+		then
+			msg_debug "proto >= 2: Receiving info.xml ..."
+			CST_OUTPUT_INFO="$CST_OUTPUT_SNAPSHOT_DIR/info.xml"
+			( read THE_BASE64 || exit; umask 077 || exit; base64 --decode >"$CST_OUTPUT_INFO" <<<"$THE_BASE64" ) || die "Receiving snapshot \"$CST_RECEIVE_SNAPSHOT_NUMBER\": Failed in \"$CST_OUTPUT_INFO\" data"
+			( read THE_DATE || exit; touch --date="$THE_DATE" "$CST_OUTPUT_INFO" ) || die "Receiving snapshot \"$CST_RECEIVE_SNAPSHOT_NUMBER\": Failed in \"$CST_OUTPUT_INFO\" timestamp"
+		fi
 
 		# Answer with received UUID, to get the protocol going again...
 		CST_SNAPSHOT_NUMBER="$CST_RECEIVE_SNAPSHOT_NUMBER"
diff --git a/lib/cvnsnapper-toolbox/replicate-send b/lib/cvnsnapper-toolbox/replicate-send
--- a/lib/cvnsnapper-toolbox/replicate-send
+++ b/lib/cvnsnapper-toolbox/replicate-send
@@ -122,7 +122,7 @@ then
 	CST_EXPECTED_OTHER_SIDE="CVNSNAPPER_REPLICATE_RECEIVER"
 
 	CST_THIS_PROTO_MIN=0
-	CST_THIS_PROTO=1
+	CST_THIS_PROTO=2
 	CST_STATE_OTHER_PROTO=
 
 
@@ -340,7 +340,15 @@ do
 		remote)
 			echo "$CST_THIS_SIDE receive $SNAPSHOT_NUMBER" >&"$CST_SSH_STDIN" || die "Failed to send protocol message for the remote host to receive snapshot number \"$SNAPSHOT_NUMBER\""
 			btrfs send -p "$INPUT_PARENT_SNAPSHOT" "$INPUT_SNAPSHOT" >&"$CST_SSH_STDIN" || die "Sending \"btrfs send\" stream to remote host failed"
-			# TODO: Somehow also transfer the info.xml!
+
+			# Since proto 2, also transfer the info.xml, in-band.
+			if [ "$CST_THIS_PROTO" -ge 2 ]
+			then
+				msg_debug "proto >= 2: Sending info.xml ..."
+				INPUT_INFO="$SNAPSHOT_NUMBER/info.xml"
+				( base64 --wrap=0 "$INPUT_INFO"; RET="$?"; echo || exit; exit "$RET" ) >&"$CST_SSH_STDIN" || die "Sending \"$INPUT_INFO\" data to remote host failed"
+				date -Ins --reference="$INPUT_INFO" >&"$CST_SSH_STDIN" || die "Sending \"$INPUT_INFO\" timestamp to remote host failed"
+			fi
 
 			read CST_OTHER_WHO CST_OTHER_WHAT CST_OTHER_REST <&"$CST_SSH_STDOUT" || die "Couldn't read send stream response message from remote host"
 			[ "$CST_OTHER_WHO" = "$CST_EXPECTED_OTHER_SIDE" ] || die "Invalid other side message: By \"$CST_OTHER_WHO\""
