replicate-send: Re-use pre-existing SNAPSHOT_INFO variable

diff --git a/lib/cvnsnapper-toolbox/replicate-send b/lib/cvnsnapper-toolbox/replicate-send
--- a/lib/cvnsnapper-toolbox/replicate-send
+++ b/lib/cvnsnapper-toolbox/replicate-send
@@ -349,9 +349,8 @@ do
 			if [ "$CST_THIS_PROTO" -ge 2 ]
 			then
 				msg_debug "proto >= 2: Sending info.xml ..."
-				INPUT_INFO="$SNAPSHOT_NUMBER/info.xml"
-				( base64 --wrap=0 "$INPUT_INFO"; RET="$?"; echo || exit; exit "$RET" ) >&"$CST_SSH_STDIN" || die "Sending \"$INPUT_INFO\" data to remote host failed"
-				date -Ins --reference="$INPUT_INFO" >&"$CST_SSH_STDIN" || die "Sending \"$INPUT_INFO\" timestamp to remote host failed"
+				( base64 --wrap=0 "$SNAPSHOT_INFO"; RET="$?"; echo || exit; exit "$RET" ) >&"$CST_SSH_STDIN" || die "Sending \"$SNAPSHOT_INFO\" data to remote host failed"
+				date -Ins --reference="$SNAPSHOT_INFO" >&"$CST_SSH_STDIN" || die "Sending \"$SNAPSHOT_INFO\" timestamp to remote host failed"
 			fi
 
 			read CST_OTHER_WHO CST_OTHER_WHAT CST_OTHER_REST <&"$CST_SSH_STDOUT" || die "Couldn't read send stream response message from remote host"
