replicate-send: Fix logic error w.r.t. which side of the SSH connection to use

diff --git a/lib/cvnsnapper-toolbox/replicate-send b/lib/cvnsnapper-toolbox/replicate-send
--- a/lib/cvnsnapper-toolbox/replicate-send
+++ b/lib/cvnsnapper-toolbox/replicate-send
@@ -84,7 +84,7 @@ then
 		[ "$CST_OTHER_REST" -eq "$LAST_SNAPSHOT_NUMBER_ARG" ] || warn "Warning: Snapshot number the remote has, \"$CST_OTHER_REST\", and that we will be using, \"$LAST_SNAPSHOT_NUMBER_ARG\", don't match"
 	fi
 
-	echo "$CST_THIS_SIDE can $LAST_SNAPSHOT_NUMBER_ARG" >&"$CST_SSH_STDOUT" || die "Couldn't send protocol message reply that we \"can\" snapshot number \"$LAST_SNAPSHOT_NUMBER_ARG\""
+	echo "$CST_THIS_SIDE can $LAST_SNAPSHOT_NUMBER_ARG" >&"$CST_SSH_STDIN" || die "Couldn't send protocol message reply that we \"can\" snapshot number \"$LAST_SNAPSHOT_NUMBER_ARG\""
 
 
 	read CST_OTHER_WHO CST_OTHER_WHAT CST_OTHER_REST <&"$CST_SSH_STDOUT" || die "Couldn't read 2nd message from remote host"
